name: cultural_tegal
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_dotenv: ^6.0.1
  supabase_flutter: ^2.12.4
  google_sign_in: ^7.2.0
  http: ^1.6.0
  flutter_secure_storage: ^10.2.0
  flutter_launcher_icons: ^0.14.4
  onesignal_flutter: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/register/register_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/register/register_icon.png
    - assets/images/beranda/cover_atas.png
    - assets/images/login/cover_login.png
    - assets/images/login/google_icon.png
    - assets/images/
    - assets/images/jelajah/cover_info_badge.png