name: cultural_tegal
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/register/1.png
    - assets/images/beranda/cover_atas.png
    - assets/images/login/cover_login.png
    - assets/images/login/google_icon.png
    - assets/images/
    - assets/images/jelajah/cover_info_badge.png